### ISSUE TITLE
1sec delay in c library when MQTTAsync_destroy is called . 

### ISSUE THREAD

**Issue by shashankanayak** [eclipse-paho/paho.mqtt.c#1107] opened 2021-05-26 10:56 UTC
issue is that  MQTTAsync_destroy is taking 1 second due MQTTAsync_receiveThread which has select timeout of 1000L.(1sec)
Can we fix this issue, in our embedded device this is considerable delay,which is bringing latency between our microservices.
micoservice-a---->microservice b
we are using request reply pattern of paho c++ library
where we are getting a roundtrip delay of 1sec.[[Delay is from the c library as pointed above not in the transport]](since the communication is on same system we expect the delay to be less than 100ms )[[usbus and msgq gives 0.1millisecond latency]]

**Comment by icraggs** [comment] 2021-05-27 09:18
I presume this doesn't happen all the time?  You should supply a trace as requested in the issue template.

**Comment by shashankanayak** [comment] 2021-05-27 10:00
Hi @icraggs ,
As suggested please find new set of logs attached.with log level with performance flag disabled.
export MQTT_C_CLIENT_TRACE_LEVEL=PROTOCOL,MAXIMUM,MEDIUM attached.

[log_maximum.txt](https://github.com/eclipse/paho.mqtt.c/files/6553021/log_maximum.txt)
[log_protcol.txt](https://github.com/eclipse/paho.mqtt.c/files/6553022/log_protcol.txt)
[log_medium.txt](https://github.com/eclipse/paho.mqtt.c/files/6553023/log_medium.txt)
Issue is reproducible all the time.

**Comment by koalo** [comment] 2021-12-03 09:14
I have the very same problem, but it is a little bit tricky, because it depends on some preconditions. But if they are fulfilled, the problem occurs nearly every time.
For me these preconditions are:
- PAHO_HIGH_PERFORMANCE=ON
- A low log level. That is the reason the problem does not occur in the logs above for maximum and medium, but only for protocol.
- The connection was made to a MQTT server running on localhost
- No valgrind or thread sanitizer is used

I have added some source code below to reproduce this problem. I also have some Python scripts that I used to make some statistics to trace down the problem, because I thought I can somehow bisect the problem, but that approach led nowhere. I can share them if they are of any help.

One side note: I had the same problem also during the connection phase, but that seems to have been fixed with https://github.com/eclipse/paho.mqtt.c/commit/0372393c3f7af00026b626ab6b5a5a27c69c9bfc. Before the fix there was nearly every time a one second delay during connection and with the fix the delay is at most 100 ms, but usually only in the range of 5 ms. So thanks a lot for fixing that!! :-)

Still, for the destroy the problem persists. If you look at the preconditions it is apparently very sensitive to timing. It also vanishes if you add some (100 ms) delay before Socket_getReadySocket in MQTTAsync_cycle. My assumption is that the problem occurs if the ``select`` in ``Socket_getReadySocket`` is called before ``MQTTAsync_stop`` is called. This leads to ``select`` blocking until the one second timeout. Unfortunately, I am unsure about the best way to solve that (maybe by using the self-pipe trick?). @icraggs do you have a spontaneous idea? Otherwise, I will further try to dive into the code to try to find a solution.

```
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include "MQTTAsync.h"
#include <pthread.h>
#include <sys/time.h>

#define ADDRESS     "tcp://localhost:1883"
#define CLIENTID    "ExampleClientPub"

pthread_cond_t connected = PTHREAD_COND_INITIALIZER;
pthread_mutex_t lock = PTHREAD_MUTEX_INITIALIZER;

void logging(const char* s) {
	struct timeval tv;
	gettimeofday(&tv,NULL);
	printf("logging %ld.%03ld %s\n",tv.tv_sec,tv.tv_usec/1000,s);
}

void onConnect(void* context, MQTTAsync_successData* response)
{
	pthread_mutex_lock(&lock);
	pthread_cond_signal(&connected);
	pthread_mutex_unlock(&lock);
}

int main(int argc, char* argv[])
{
	logging("start");
	MQTTAsync client;
	MQTTAsync_connectOptions conn_opts = MQTTAsync_connectOptions_initializer;
	MQTTAsync_message pubmsg = MQTTAsync_message_initializer;
	MQTTAsync_token token;
	int rc;
	MQTTAsync_create(&client, ADDRESS, CLIENTID, MQTTCLIENT_PERSISTENCE_NONE, NULL);
	conn_opts.keepAliveInterval = 20;
	conn_opts.cleansession = 1;
	conn_opts.onSuccess = onConnect;
	conn_opts.context = client;
	if ((rc = MQTTAsync_connect(client, &conn_opts)) != MQTTASYNC_SUCCESS)
	{
		printf("Failed to start connect, return code %d\n", rc);
		exit(EXIT_FAILURE);
	}

	logging("waiting");

	pthread_mutex_lock(&lock);
	pthread_cond_wait(&connected, &lock);
	pthread_mutex_unlock(&lock);

	logging("connected");

	MQTTAsync_destroy(&client);

	logging("destroyed");

	return rc;
}
```

Log with the delay:
```
logging 1638522083.015 start
=========================================================
                   Trace Output
Product name: Eclipse Paho Asynchronous MQTT C Client Library
Version: 1.3.9
Build level: 2021-12-03T08:51:34Z
OpenSSL version: OpenSSL 1.1.1f  31 Mar 2020
OpenSSL flags: compiler: gcc -fPIC -pthread -m64 -Wa,--noexecstack -Wall -Wa,--noexecstack -g -O2 -fdebug-prefix-map=/build/openssl-xajkZk/openssl-1.1.1f=. -fstack-protector-strong -Wformat -Werror=format-security -DOPENSSL_TLS_SECURITY_LEVEL=2 -DOPENSSL_USE_NODELETE -DL_ENDIAN -DOPENSSL_PIC -DOPENSSL_CPUID_OBJ -DOPENSSL_IA32_SSE2 -DOPENSSL_BN_ASM_MONT -DOPENSSL_BN_ASM_MONT5 -DOPENSSL_BN_ASM_GF2m -DSHA1_ASM -DSHA256_ASM -DSHA512_ASM -DKECCAK1600_ASM -DRC4_ASM -DMD5_ASM -DAESNI_ASM -DVPAES_ASM -DGHASH_ASM -
OpenSSL build timestamp: built on: Wed Aug 25 01:13:44 2021 UTC
OpenSSL platform: platform: debian-amd64
OpenSSL directory: OPENSSLDIR: "/usr/lib/ssl"
/proc/version: Linux version 5.4.0-90-generic (buildd@lgw01-amd64-054) (gcc version 9.3.0 (Ubuntu 9.3.0-17ubuntu1~20.04)) #101-Ubuntu SMP Fri Oct 15 20:00:55 UTC 2021

=========================================================
19700101 010000.000 0 commands restored for client ExampleClientPub
19700101 010000.000 0 queued messages restored for client ExampleClientPub
logging 1638522083.019 waiting
19700101 010000.000 Connecting to serverURI localhost:1883 with MQTT version 4
19700101 010000.000 New socket 3 for localhost:1883, port 1883
19700101 010000.000 Connect pending
19700101 010000.000 Return code 1 from read select
19700101 010000.000 Return code 1 from write select
19700101 010000.000 m->c->connect_state = 1
19700101 010000.000 3 ExampleClientPub -> CONNECT version 4 clean: 1 (0)
19700101 010000.000 Return code 1 from read select
19700101 010000.000 Return code 1 from write select
19700101 010000.000 m->c->connect_state = 4
19700101 010000.000 queueChar: index is now 1, headerlen 1
19700101 010000.000 queueChar: index is now 2, headerlen 2
19700101 010000.000 3 ExampleClientPub <- CONNACK rc: 0
19700101 010000.000 0 inflight messages deleted for client ExampleClientPub
19700101 010000.000 0 responses removed for client ExampleClientPub
19700101 010000.000 Calling connect success for client ExampleClientPub
logging 1638522083.020 connected
19700101 010000.000 3 ExampleClientPub -> DISCONNECT (0)
20211203 100123.021 Removed socket 3
20211203 100123.021 Reset max fdp1 to 1
20211203 100123.021 0 inflight messages deleted for client ExampleClientPub
20211203 100123.021 0 responses removed for client ExampleClientPub
20211203 100123.021 0 responses removed for client ExampleClientPub
20211203 100123.021 0 commands removed for client ExampleClientPub
20211203 100123.021 Removed client ExampleClientPub from bstate->clients, socket 0
20211203 100123.021 Conn_count is 0
20211203 100123.021 sleeping
20211203 100123.021 sleeping
20211203 100123.021 sleeping
20211203 100123.021 sleeping
20211203 100123.021 sleeping
20211203 100123.021 sleeping
20211203 100123.021 sleeping
20211203 100123.021 sleeping
20211203 100123.021 sleeping
20211203 100123.021 sleeping
20211203 100123.021 Return code 0 from read select
20211203 100123.021 Return code 0 from write select
logging 1638522084.024 destroyed
```

Log without the delay:
```
logging 1638522077.031 start
=========================================================
                   Trace Output
Product name: Eclipse Paho Asynchronous MQTT C Client Library
Version: 1.3.9
Build level: 2021-12-03T08:51:34Z
OpenSSL version: OpenSSL 1.1.1f  31 Mar 2020
OpenSSL flags: compiler: gcc -fPIC -pthread -m64 -Wa,--noexecstack -Wall -Wa,--noexecstack -g -O2 -fdebug-prefix-map=/build/openssl-xajkZk/openssl-1.1.1f=. -fstack-protector-strong -Wformat -Werror=format-security -DOPENSSL_TLS_SECURITY_LEVEL=2 -DOPENSSL_USE_NODELETE -DL_ENDIAN -DOPENSSL_PIC -DOPENSSL_CPUID_OBJ -DOPENSSL_IA32_SSE2 -DOPENSSL_BN_ASM_MONT -DOPENSSL_BN_ASM_MONT5 -DOPENSSL_BN_ASM_GF2m -DSHA1_ASM -DSHA256_ASM -DSHA512_ASM -DKECCAK1600_ASM -DRC4_ASM -DMD5_ASM -DAESNI_ASM -DVPAES_ASM -DGHASH_ASM -
OpenSSL build timestamp: built on: Wed Aug 25 01:13:44 2021 UTC
OpenSSL platform: platform: debian-amd64
OpenSSL directory: OPENSSLDIR: "/usr/lib/ssl"
/proc/version: Linux version 5.4.0-90-generic (buildd@lgw01-amd64-054) (gcc version 9.3.0 (Ubuntu 9.3.0-17ubuntu1~20.04)) #101-Ubuntu SMP Fri Oct 15 20:00:55 UTC 2021

=========================================================
19700101 010000.000 0 commands restored for client ExampleClientPub
19700101 010000.000 0 queued messages restored for client ExampleClientPub
logging 1638522077.035 waiting
19700101 010000.000 Connecting to serverURI localhost:1883 with MQTT version 4
19700101 010000.000 New socket 3 for localhost:1883, port 1883
19700101 010000.000 Connect pending
19700101 010000.000 Return code 1 from read select
19700101 010000.000 Return code 1 from write select
19700101 010000.000 m->c->connect_state = 1
19700101 010000.000 3 ExampleClientPub -> CONNECT version 4 clean: 1 (0)
19700101 010000.000 Return code 1 from read select
19700101 010000.000 Return code 1 from write select
19700101 010000.000 m->c->connect_state = 4
19700101 010000.000 queueChar: index is now 1, headerlen 1
19700101 010000.000 queueChar: index is now 2, headerlen 2
19700101 010000.000 3 ExampleClientPub <- CONNACK rc: 0
19700101 010000.000 0 inflight messages deleted for client ExampleClientPub
19700101 010000.000 0 responses removed for client ExampleClientPub
19700101 010000.000 Calling connect success for client ExampleClientPub
logging 1638522077.036 connected
19700101 010000.000 3 ExampleClientPub -> DISCONNECT (0)
20211203 100117.036 Removed socket 3
20211203 100117.036 Reset max fdp1 to 1
20211203 100117.036 0 inflight messages deleted for client ExampleClientPub
20211203 100117.036 0 responses removed for client ExampleClientPub
20211203 100117.036 0 responses removed for client ExampleClientPub
20211203 100117.036 0 commands removed for client ExampleClientPub
20211203 100117.036 Removed client ExampleClientPub from bstate->clients, socket 0
20211203 100117.036 Conn_count is 0
20211203 100117.036 sleeping
20211203 100117.036 Return code 1 from read select
20211203 100117.036 Return code 0 from write select
logging 1638522077.136 destroyed
```

**Closed as completed** 2022-03-28 15:56 UTC
Labels: fix added
