### ISSUE TITLE
Low keepAlive Interval results in frequent disconnects

### ISSUE THREAD

**Issue by mqdeandrade** [eclipse-paho/paho.mqtt.c#619] opened 2019-03-01 18:14 UTC
Good Day

I am developing a device that has an MQTT connection to our server for data transfer. The device needs to be able to notify the end user of a connection issue. User interactions with the device are usual in the order of 10s. To this end I monitor the connection lost callback and notify the user once this callback is fired.

The issue I encounter is that a keepAliveInterval of below 20s will result in frequent lost connections, even if the connection to the server is actually sound. A keepAliveInterval of 20 or above however will mean that the user could only be notified of a lost connection just over 20 seconds after the connection drops, which, since the mean time of interaction with the device is 10s, is undesirable.

As a workaround I have set the keepAliveInterval to 10s and set a loop within my program to send a psuedo-ping (just a blank message) however I believe that there must be a more elegant solution. As far as I understand the MQTT spec, the client should send a PINREQ to the server if there is no communication within the keepAliveInterval. While this mechanism does seem to work, for keepAliveInterval intervals below 20s the connection is marked as dead before the client has time to receive the PINGRESP.

I don't know whether the solution is to increase the frequency at which the PINGREQ is sent relative to the keepAliveInterval or increase the timeout between sending the PINGREQ and marking the connection as dead when the PINGRESP isn't received. Perhaps I don't understand the protocol well enough...

paho.mqtt.c V1.3.1
mosquitto V1.5.4

**Comment by icraggs** [comment] 2020-10-29 16:29
Duplicate of #590

**Closed as completed** 2020-11-21 20:21 UTC
Labels: duplicate, fix added
