### ISSUE TITLE
The previous issue(#243). The return value of connect in the function Socket_new in Socket.c is SOCKET_ERROR, but the specfic error is WSA_INVALID_HANDLE.

### ISSUE THREAD

**Issue by guobaoteacher** [eclipse-paho/paho.mqtt.c#248] opened 2017-04-10 01:33 UTC
Hi, 
    Excuse me. Thank you at first. I have already normalized the error. But if I use the library created by VS2012 instead of the source code before I normalized the error, there is no such error. Here is my configuration:
OS: Win32
Compiler: VS2012
    Thank you again.

**Comment by icraggs** [comment] 2017-04-11 13:01
Hi.
I don't understand what the issue is.   Socket_new should return SOCKET_ERROR if there is an error.  Are you saying there shouldn't be an error?  What is the scenario?  Do you have a test program?  Can you get a trace by setting the following environment variable?

MQTT_C_CLIENT_TRACE=ON

**Comment by guobaoteacher** [comment] 2017-04-11 13:23
`else
			{
				/* this could complete immmediately, even though we are non-blocking */
				if (family == AF_INET)
					rc = connect(*sock, (struct sockaddr*)&address, sizeof(address));
	#if defined(AF_INET6)
				else
					rc = connect(*sock, (struct sockaddr*)&address6, sizeof(address6));
	#endif
				if (rc == SOCKET_ERROR)
					rc = Socket_error("connect", *sock);
				if (rc == EINPROGRESS || rc == EWOULDBLOCK)
				{
					int* pnewSd = (int*)malloc(sizeof(int));
					*pnewSd = *sock;
					ListAppend(s.connect_pending, pnewSd, sizeof(int));
					Log(TRACE_MIN, 15, "Connect pending");
				}
			}`
  Year, the return value of 'rc = connect(*sock, (struct sockaddr*)&address, sizeof(address));' is SOCKET_ERROR. But the return value of 'rc = Socket_error("connect", *sock);' is 6, i.e. WSA_INVALID_HANDLE. I use the souce code in my program. If I use the library as DLL, there is no such problem. The return value of MQTTClient_connect is 0, i.e. the connect is successful. I am a greehand. I will try to get a trace. Thank you very much.

**Comment by guobaoteacher** [comment] 2017-04-11 13:27
Here is part of Socker_new in Socket.c :
```
else
			{
				/* this could complete immmediately, even though we are non-blocking */
				if (family == AF_INET)
					rc = connect(*sock, (struct sockaddr*)&address, sizeof(address));
	#if defined(AF_INET6)
				else
					rc = connect(*sock, (struct sockaddr*)&address6, sizeof(address6));
	#endif
				if (rc == SOCKET_ERROR)
					rc = Socket_error("connect", *sock);
				if (rc == EINPROGRESS || rc == EWOULDBLOCK)
				{
					int* pnewSd = (int*)malloc(sizeof(int));
					*pnewSd = *sock;
					ListAppend(s.connect_pending, pnewSd, sizeof(int));
					Log(TRACE_MIN, 15, "Connect pending");
				}
			}
		}
```
  Year, the return value of 'rc = connect(sock, (struct sockaddr)&address, sizeof(address));' is SOCKET_ERROR. But the return value of 'rc = Socket_error("connect", *sock);' is 6, i.e. WSA_INVALID_HANDLE. So the return value of Socket_new is 6. I use the souce code in my program. If I use the library as DLL created by VS, there is no such problem. The return value of MQTTClient_connect is 0, i.e. the connect is successful. I am a greenhand. I will try to get a trace.  I will appreciate your comments. Thank you very much.

**Comment by guobaoteacher** [comment] 2017-04-11 13:29
`else
			{
				/* this could complete immmediately, even though we are non-blocking */
				if (family == AF_INET)
					rc = connect(*sock, (struct sockaddr*)&address, sizeof(address));
	#if defined(AF_INET6)
				else
					rc = connect(*sock, (struct sockaddr*)&address6, sizeof(address6));
	#endif
				if (rc == SOCKET_ERROR)
					rc = Socket_error("connect", *sock);
				if (rc == EINPROGRESS || rc == EWOULDBLOCK)
				{
					int* pnewSd = (int*)malloc(sizeof(int));
					*pnewSd = *sock;
					ListAppend(s.connect_pending, pnewSd, sizeof(int));
					Log(TRACE_MIN, 15, "Connect pending");
				}
			}
`

**Comment by icraggs** [comment] 2017-04-28 12:04
Socket_error() is working as intended.  Socket_error calls WSAGetLastError() which "returns the error status for the last Windows Sockets operation that failed", in your case WSA_INVALID_HANDLE.  It's up to you to handle that error.

**Comment by icraggs** [comment] 2017-05-09 09:24
I think I've answered this question - closing.

**Closed as completed by icraggs** 2017-05-09 09:24 UTC
Labels: question
