### ISSUE TITLE
Log() function name conflict

### ISSUE THREAD

**Issue by akshirasagar** [eclipse-paho/paho.mqtt.c#355] opened 2017-11-03 06:45 UTC
I am using the paho mqtt c library in a project. The paho mqtt c library contains a Log() function in the Log.c, at line 394. This conflicts with one of our functions with the same name but different arguments. 
We require to use our Log() function in the project, because this is part of our legacy code and already used/will be used in existing/future deployments. 
So I would suggest that in future releases of the paho library, this (and maybe other) functions be renamed suitably so this can be used without any name conflicts.

**Comment by icraggs** [comment] 2017-11-03 11:00
In the shared libraries, the only functions that should be exported are those tagged with "DLLExport".  All the other functions should be internal only.

**Comment by icraggs** [comment] 2017-11-16 11:55
I think this is a duplicate of #132

**Closed as completed by icraggs** 2017-11-16 11:55 UTC
Labels: duplicate
