### ISSUE TITLE
What is the use of storing SUBSCRIBE message in the persistence file?

### ISSUE THREAD

**Issue by bansalaj** [eclipse-paho/paho.mqtt.c#1112] opened 2021-06-06 16:20 UTC
What is the use of storing SUBSCRIBE message in the persistence file, and if we are storing then why not storing the full details?
To me it really doesn't make sense to store the SUBSCRIBE message, because on successful connection to the server, client can always send the SUBSCRIBE message to the server through success callback.

_Originally posted by @halfbakedbro in https://github.com/eclipse/paho.mqtt.c/issues/1108#issuecomment-855423792_

**Comment by icraggs** [comment] 2021-07-09 11:25
The subscribe is stored in the persistence file when it is put onto the command queue, which stores all commands before they are sent over TCP/IP.  Also, as a QoS 1 message, it could be retried on connection re-establishment.

I see this is a duplicate of #1108.  I''ll close this and put this answer in there also.

**Closed as completed by icraggs** 2021-07-09 11:25 UTC
Labels: duplicate
