### ISSUE TITLE
Cannot connect to mosquitto when client certs are mandatory.

### ISSUE THREAD

**Issue by jameswhite** [eclipse-paho/paho.mqtt.c#216] opened 2017-01-24 01:32 UTC
When I try to connect a paho.mqtt.c client to a mosquitto server that requires client certs, the mosquitto.log complains with:

```
==> default: 1485189674: New connection from 127.0.0.1 on port 8883.
==> default: 1485189674: OpenSSL Error: error:1408F10B:SSL routines:SSL3_GET_RECORD:wrong version number
==> default: 1485189674: Socket error on client (null), disconnecting.
``` 

I've created a [vagrantfile](https://github.com/jameswhite/hates.software/blob/master/software/paho.mqtt.c/vagrantfile) that will demonstrate this by:

  - [ ] Create a PKI: a certificate authority and a couple certificates for our mqtt server and client
  - [ ] Add /etc/hosts entries so that the certificates match the hostnames
  - [ ] Install and configure mosquitto with the server certificate from our PKI
  - [ ] Compile paho.mqtt.c and our test case of paho.mqtt.c with client certificates connecting to our mqtts://mqtt.hates.software:8883
  - [ ] Run our tests using the client cert
  - [ ] Dump the mosquitto.log

When I connect with [openssl s_client] to the mosquitto server it validates properly. Clients in [javascript](https://github.com/websages/standing-water/blob/master/scripts/client_cert.js), [ruby](https://github.com/websages/standing-water/blob/master/scripts/client_cert.rb), and [perl](https://github.com/websages/standing-water/blob/master/scripts/client_cert.pl) can connect to the mosquitto server with the same client certificates passed to the paho.mqtt.c client, which is just a copy of [test2a_m in test/test3.c](https://github.com/eclipse/paho.mqtt.c/blob/master/test/test3.c#L708-L783) modified for the vagrant box.

**Comment by icraggs** [comment] 2017-04-06 15:40
Hi James. 

This is caused by not including the "ssl://" prefix in the connection string to the MQTTClient_create() call.  The original test3.c included this prefix.  I added the prefix it to your test program connection strings, and that worked for me.   Obviously just getting "wrong version number" on the server isn't very helpful.  I'll think about what could be done.

**Comment by jameswhite** [comment] 2017-04-08 20:44
Ah I think I removed that because it'd give me:
```
20170408 203721.694 getaddrinfo failed for addr ssl://mqtt.hates.software with rc -2
20170408 203721.694 ssl://mqtt.hates.software is not a valid IP address
20170408 203725.951 getaddrinfo failed for addr ssl://mqtt.hates.software with rc -2
20170408 203725.951 ssl://mqtt.hates.software is not a valid IP address
Assertion failed, file /var/cache/git/hates.software/software/paho.mqtt.c/client_cert.c, line 598, description: Good rc from connect
rc was -120170408 203726.054 failed: test test2a_m. 3 tests run, 1 failures.
20170408 203726.054 Total tests run: 3
20170408 203726.055 verdict fail
```

or if I used an IP:

```
20170408 203849.033 getaddrinfo failed for addr ssl://10.0.2.15 with rc -2
20170408 203849.033 ssl://10.0.2.15 is not a valid IP address
20170408 203849.253 getaddrinfo failed for addr ssl://10.0.2.15 with rc -2
20170408 203849.253 ssl://10.0.2.15 is not a valid IP address
Assertion failed, file /var/cache/git/hates.software/software/paho.mqtt.c/client_cert.c, line 598, description: Good rc from connect
rc was -120170408 203849.356 failed: test test2a_m. 3 tests run, 1 failures.
20170408 203849.356 Total tests run: 3
20170408 203849.356 verdict fail
```

and the `getaddrinfo failed` errors go away if I remove the `ssl://` but I still get Assertion Failed with 'ssl://'

**Comment by icraggs** [comment] 2017-04-24 14:32
I only get that exact error message when I link against the non-SSL enabled version of the library.  The name of the SSL enabled version ends with 's'.  

So:

gcc -I /usr/local/include -L /usr/local/lib -lpaho-mqtt3c -o /tmp/client_cert /var/cache/git/hates.software/software/paho.mqtt.c/client_cert.c -lpaho-mqtt3c

should be:

gcc -I /usr/local/include -L /usr/local/lib -lpaho-mqtt3cs -o /tmp/client_cert /var/cache/git/hates.software/software/paho.mqtt.c/client_cert.c -lpaho-mqtt3cs

I must have changed that too to get your test to work.  There is another recent issue (#251) raised to return a proper error code if the non-SSL version of the library is used with an SSL request.

**Comment by icraggs** [comment] 2017-05-05 10:30
The change to produce an error if requesting SSL/TLS when running against the non-TLS enabled version of the library has been added to the develop branch.  With that, I think this issue is resolved.

**Comment by icraggs** [comment] 2017-07-19 14:02
Closing, as I believe the better error reporting in 1.2 resolves the issue.

**Closed as completed by icraggs** 2017-07-19 14:02 UTC
Labels: enhancement
