### ISSUE TITLE
OpenSSL Memory problem caused while using paho-mqtt3as

### ISSUE THREAD

**Issue by jaysontatum87** [eclipse-paho/paho.mqtt.c#1019] opened 2020-12-11 02:18 UTC
I detected memory leak by using _CrtDumpMemoryLeaks when closed process.
I had tried the methods mentioned on https://wiki.openssl.org/index.php/Library_Initialization#Cleanup
to clean up memory but it was not fixed.

It is fixed with #316 on 1.3.9?

_Originally posted by @jaysontatum87 in https://github.com/eclipse/paho.mqtt.c/issues/925#issuecomment-742168184_

**Comment by icraggs** [comment] 2020-12-11 11:38
I don't know.  I haven't started working on 1.3.9 yet.  What version of OpenSSL are you using (different calls are needed for different versions)?  

You might know as much as I do at this point by looking at that documentation.  

This is also a duplicate of #316 to be looked at in 1.3.9.

**Comment by jaysontatum87** [comment] 2020-12-13 05:37
My OpenSSL version is  1.0.2u.
The functions as follow could release a part of memory but not the all:
`CRYPTO_cleanup_all_ex_data();`
`SSL_COMP_free_compression_methods();`

**Comment by jaysontatum87** [comment] 2020-12-15 12:06
I also found  that different memory leak results were caused by setting the cleansession option  as follow,

**conn_opts(MQTTAsync_connectOption).cleansession = 0;**
and
**conn_opts.cleansession = 1;**


I had a look at MqttAsync.c but could't figure out where unreleased memory is.
[tracelog.txt](https://github.com/eclipse/paho.mqtt.c/files/5695659/tracelog.txt) also shows that all heap memory had been released. 
Should I change to upper version openSSL to test memory?


when set  cleansession=0, a part of memory is released.

1.  memory leak result which without using cleaing up function.
[1.cleansession=0,without_cleaing_up_function.txt](https://github.com/eclipse/paho.mqtt.c/files/5695569/1.cleansession.0.without_cleaing_up_function.txt)

2.  memory leak result which used cleaing up function.
[2.cleansession=0,used_cleaing_up_function.txt](https://github.com/eclipse/paho.mqtt.c/files/5695567/2.cleansession.0.used_cleaing_up_function.txt)

when set cleansession=1, the memory is almost released.

 3.  memory leak result which without using cleaing up function.
[3.cleansession=1,without_cleaing_up_function.txt](https://github.com/eclipse/paho.mqtt.c/files/5695574/3.cleansession.1.without_cleaing_up_function.txt)

4.  memory leak result which used cleaing up function.
[4.cleansession=1,used_cleaing_up_function.txt](https://github.com/eclipse/paho.mqtt.c/files/5695494/4.cleansession.1.used_cleaing_up_function.txt)

**Comment by icraggs** [comment] 2021-01-12 13:56
Going to track this in #316

**Closed as completed by icraggs** 2021-01-12 13:56 UTC
Labels: duplicate
