### ISSUE TITLE
OPENSSL memory leaks after MQTTClient_destroy

### ISSUE THREAD

**Issue by paulborile** [eclipse-paho/paho.mqtt.c#670] opened 2019-06-27 16:58 UTC
Hi,

we are MQTTClient apis ( MQTTClient_create(), MQTTClient_setCallbacks(), MQTTClient_connect(), MQTTClient_publishMessage(), MQTTClient_(un)subscribe(), MQTTClient_destroy() ) and using gcc sanitizer ( -fsanitize=address ) these are the reported leaks (I'll try to get the full stack of the leaked calls asap) : 

`==7515==ERROR: LeakSanitizer: detected memory leaks

Direct leak of 4448 byte(s) in 1 object(s) allocated from:
#0 0x7fd17001fb50 in __interceptor_malloc (/usr/lib/x86_64-linux-gnu/libasan.so.4+0xdeb50)
#1 0x7fd16dfd54b8 in CRYPTO_zalloc (/usr/lib/x86_64-linux-gnu/libcrypto.so.1.1+0x1574b8)

Indirect leak of 17920 byte(s) in 276 object(s) allocated from:
#0 0x7fd17001fb50 in __interceptor_malloc (/usr/lib/x86_64-linux-gnu/libasan.so.4+0xdeb50)
#1 0x7fd16dfd54b8 in CRYPTO_zalloc (/usr/lib/x86_64-linux-gnu/libcrypto.so.1.1+0x1574b8)

Indirect leak of 16712 byte(s) in 1 object(s) allocated from:
#0 0x7fd17001fb50 in __interceptor_malloc (/usr/lib/x86_64-linux-gnu/libasan.so.4+0xdeb50)
#1 0x7fd16e3146bb (/usr/lib/x86_64-linux-gnu/libssl.so.1.1+0x1e6bb)

Indirect leak of 16560 byte(s) in 1 object(s) allocated from:
#0 0x7fd17001fb50 in __interceptor_malloc (/usr/lib/x86_64-linux-gnu/libasan.so.4+0xdeb50)
#1 0x7fd16e3147b1 (/usr/lib/x86_64-linux-gnu/libssl.so.1.1+0x1e7b1)

Indirect leak of 3318 byte(s) in 3 object(s) allocated from:
#0 0x7fd17001fb50 in __interceptor_malloc (/usr/lib/x86_64-linux-gnu/libasan.so.4+0xdeb50)
#1 0x7fd16df0ff6f (/usr/lib/x86_64-linux-gnu/libcrypto.so.1.1+0x91f6f)

Indirect leak of 2617 byte(s) in 93 object(s) allocated from:
#0 0x7fd17001fb50 in __interceptor_malloc (/usr/lib/x86_64-linux-gnu/libasan.so.4+0xdeb50)
#1 0x7fd16df03e79 in ASN1_STRING_set (/usr/lib/x86_64-linux-gnu/libcrypto.so.1.1+0x85e79)

Indirect leak of 1280 byte(s) in 9 object(s) allocated from:
#0 0x7fd17001ff40 in realloc (/usr/lib/x86_64-linux-gnu/libasan.so.4+0xdef40)
#1 0x7fd16e027258 in OPENSSL_sk_insert (/usr/lib/x86_64-linux-gnu/libcrypto.so.1.1+0x1a9258)

Indirect leak of 810 byte(s) in 3 object(s) allocated from:
#0 0x7fd17001fb50 in __interceptor_malloc (/usr/lib/x86_64-linux-gnu/libasan.so.4+0xdeb50)
#1 0x7fd16defac4d (/usr/lib/x86_64-linux-gnu/libcrypto.so.1.1+0x7cc4d)

Indirect leak of 788 byte(s) in 6 object(s) allocated from:
#0 0x7fd17001fb50 in __interceptor_malloc (/usr/lib/x86_64-linux-gnu/libasan.so.4+0xdeb50)
#1 0x7fd16df3c0e7 in BUF_MEM_grow (/usr/lib/x86_64-linux-gnu/libcrypto.so.1.1+0xbe0e7)

Indirect leak of 563 byte(s) in 6 object(s) allocated from:
#0 0x7fd17001fb50 in __interceptor_malloc (/usr/lib/x86_64-linux-gnu/libasan.so.4+0xdeb50)
#1 0x7fd16e040c19 (/usr/lib/x86_64-linux-gnu/libcrypto.so.1.1+0x1c2c19)

Indirect leak of 544 byte(s) in 2 object(s) allocated from:
#0 0x7fd17001fb50 in __interceptor_malloc (/usr/lib/x86_64-linux-gnu/libasan.so.4+0xdeb50)
#1 0x7fd16e0274b5 in OPENSSL_sk_dup (/usr/lib/x86_64-linux-gnu/libcrypto.so.1.1+0x1a94b5)

Indirect leak of 432 byte(s) in 12 object(s) allocated from:
#0 0x7fd17001fb50 in __interceptor_malloc (/usr/lib/x86_64-linux-gnu/libasan.so.4+0xdeb50)
#1 0x7fd16dfd54b8 in CRYPTO_zalloc (/usr/lib/x86_64-linux-gnu/libcrypto.so.1.1+0x1574b8)
#2 0xa17f9e24757c48ff ()

Indirect leak of 312 byte(s) in 3 object(s) allocated from:
#0 0x7fd17001fb50 in __interceptor_malloc (/usr/lib/x86_64-linux-gnu/libasan.so.4+0xdeb50)
#1 0x7fd16df2bfb6 in BN_MONT_CTX_new (/usr/lib/x86_64-linux-gnu/libcrypto.so.1.1+0xadfb6)

Indirect leak of 256 byte(s) in 1 object(s) allocated from:
#0 0x7fd17001fb50 in __interceptor_malloc (/usr/lib/x86_64-linux-gnu/libasan.so.4+0xdeb50)
#1 0x7fd16defac4d (/usr/lib/x86_64-linux-gnu/libcrypto.so.1.1+0x7cc4d)
#2 0x61b000010d2d ()

Indirect leak of 256 byte(s) in 1 object(s) allocated from:
#0 0x7fd17001fb50 in __interceptor_malloc (/usr/lib/x86_64-linux-gnu/libasan.so.4+0xdeb50)
#1 0x7fd16defac4d (/usr/lib/x86_64-linux-gnu/libcrypto.so.1.1+0x7cc4d)
#2 0x62a00000cd92 ()

Indirect leak of 256 byte(s) in 1 object(s) allocated from:
#0 0x7fd17001fb50 in __interceptor_malloc (/usr/lib/x86_64-linux-gnu/libasan.so.4+0xdeb50)
#1 0x7fd16defac4d (/usr/lib/x86_64-linux-gnu/libcrypto.so.1.1+0x7cc4d)
#2 0x62a00000c8f7 ()

Indirect leak of 144 byte(s) in 9 object(s) allocated from:
#0 0x7fd17001fb50 in __interceptor_malloc (/usr/lib/x86_64-linux-gnu/libasan.so.4+0xdeb50)
#1 0x7fd16df0e54e (/usr/lib/x86_64-linux-gnu/libcrypto.so.1.1+0x9054e)

Indirect leak of 120 byte(s) in 1 object(s) allocated from:
#0 0x7fd17001fb50 in __interceptor_malloc (/usr/lib/x86_64-linux-gnu/libasan.so.4+0xdeb50)
#1 0x7fd16e33029f (/usr/lib/x86_64-linux-gnu/libssl.so.1.1+0x3a29f)

Indirect leak of 80 byte(s) in 2 object(s) allocated from:
#0 0x7fd17001fb50 in __interceptor_malloc (/usr/lib/x86_64-linux-gnu/libasan.so.4+0xdeb50)
#1 0x7fd16e027478 in OPENSSL_sk_dup (/usr/lib/x86_64-linux-gnu/libcrypto.so.1.1+0x1a9478)

Indirect leak of 29 byte(s) in 1 object(s) allocated from:
#0 0x7fd17001fb50 in __interceptor_malloc (/usr/lib/x86_64-linux-gnu/libasan.so.4+0xdeb50)
#1 0x7fd16dfde3be in CRYPTO_strdup (/usr/lib/x86_64-linux-gnu/libcrypto.so.1.1+0x1603be)

Indirect leak of 24 byte(s) in 1 object(s) allocated from:
#0 0x7fd17001fb50 in __interceptor_malloc (/usr/lib/x86_64-linux-gnu/libasan.so.4+0xdeb50)
#1 0x7fd16e031cb2 (/usr/lib/x86_64-linux-gnu/libcrypto.so.1.1+0x1b3cb2)

Indirect leak of 24 byte(s) in 1 object(s) allocated from:
#0 0x7fd17001fb50 in __interceptor_malloc (/usr/lib/x86_64-linux-gnu/libasan.so.4+0xdeb50)
#1 0x7fd16e031b3e (/usr/lib/x86_64-linux-gnu/libcrypto.so.1.1+0x1b3b3e)

Indirect leak of 19 byte(s) in 1 object(s) allocated from:
#0 0x7fd17001fb50 in __interceptor_malloc (/usr/lib/x86_64-linux-gnu/libasan.so.4+0xdeb50)
#1 0x7fd16dfde4ee in CRYPTO_strndup (/usr/lib/x86_64-linux-gnu/libcrypto.so.1.1+0x1604ee)
`
Any other info needed please let know

**Comment by icraggs** [comment] 2019-07-11 13:53
So these are in the OpenSSL library, I think.  I've had some discussion in the past as to whether some of the OpenSSL cleanup routines should be called, or not.  If the enclosing application is also using OpenSSL, calling them can lead to conflicts, so I remember taking one or more of them out.

**Comment by icraggs** [comment] 2020-04-23 09:44
The same as #316 I think.

**Comment by icraggs** [comment] 2020-09-29 17:32
Closing as duplicate of #316

**Closed as completed by icraggs** 2020-09-29 17:32 UTC
Labels: duplicate
