### ISSUE TITLE
Time change into the past breaks automatic reconnect

### ISSUE THREAD

**Issue by SeadexWP** [eclipse-paho/paho.mqtt.c#284] opened 2017-06-02 09:49 UTC
If the time gets changed "into the past" (manually, per NTP) then a disconnect happens and the reconnect won't work. Well it will - but in the (far) future.
The reason is that MQTTAsync_checkTimeouts fails to detect that it has to do something, because it only checks if the time difference is big enough, but it fails to check if the difference is negative, which means that a time jump into the past happens. This all is related to "last" not getting updated and being stuck "in the future".
The following change makes it work:
`void MQTTAsync_checkTimeouts()
{
	ListElement* current = NULL;
	static time_t last = 0L;
	time_t now;

	FUNC_ENTRY;
	time(&(now));

	const double difftimeRes = difftime(now, last);
	if (difftimeRes < 3) {
		if(difftimeRes < 0){
			Log(TRACE_PROTOCOL, -1, "Time change into the past detected.");
		} else {
			goto exit;
		}
	}

	MQTTAsync_lock_mutex(mqttasync_mutex);
	last = now;
	while (ListNextElement(handles, &current))		/* for each client */`

**Comment by SeadexWP** [comment] 2017-06-02 13:53
Problem repeats itself elsewhere:
MQTTAsync.c

```
void MQTTAsync_retry(void)
{
	static time_t last = 0L;
	time_t now;

	FUNC_ENTRY;
	time(&(now));

	const double diffTime = difftime(now, last);
	if((diffTime < 0) || (diffTime > 5))
	{
		time(&(last));
		MQTTProtocol_keepalive(now);
		MQTTProtocol_retry(now, 1, 0);
	}
	else
		MQTTProtocol_retry(now, 0, 0);
	FUNC_EXIT;
}
```

MQTTClient.c

```
void MQTTClient_retry(void)
{
	time_t now;

	FUNC_ENTRY;
	time(&(now));
	const double diffTime = difftime(now, last);
	if((diffTime < 0) || (diffTime > 5))
	{
		time(&(last));
		MQTTProtocol_keepalive(now);
		MQTTProtocol_retry(now, 1, 0);
	}
	else
		MQTTProtocol_retry(now, 0, 0);
	FUNC_EXIT;
}

```
MQTTProtocolCLient.c

```
void MQTTProtocol_keepalive(time_t now)
{
	ListElement* current = NULL;

	FUNC_ENTRY;
	ListNextElement(bstate->clients, &current);
	while (current)
	{
		Clients* client =	(Clients*)(current->content);

		const double lastSentDiff = difftime(now, client->net.lastSent);
		if(lastSentDiff < 0) {
			client->net.lastSent = now - client->keepAliveInterval;

			Log(TRACE_PROTOCOL, -1, "Resetting last sent.");
		}

		const double lastReceiveDiff = difftime(now, client->net.lastReceived);
		if(lastReceiveDiff < 0) {
			client->net.lastReceived = now - client->keepAliveInterval;

			Log(TRACE_PROTOCOL, -1, "Resetting last received.");
		}

		ListNextElement(bstate->clients, &current); 
		if (client->connected && client->keepAliveInterval > 0 &&
				(difftime(now, client->net.lastSent) >= client->keepAliveInterval |
```|
			

```
void MQTTProtocol_retries(time_t now, Clients* client, int regardless)
{
	ListElement* outcurrent = NULL;

	FUNC_ENTRY;

	if (!regardless && client->retryInterval <= 0) /* 0 or -ive retryInterval turns off retry except on reconnect */
		goto exit;

	while (client && ListNextElement(client->outboundMsgs, &outcurrent) &&
			client->connected && client->good &&        /* client is connected and has no errors */
			Socket_noPendingWrites(client->net.socket)) /* there aren't any previous packets still stacked up on the socket */
	{
		Messages* m = (Messages*)(outcurrent->content);

		const double diffTime = difftime(now, m->lastTouch);
		if(diffTime < 0){
			m->lastTouch = now;
		}

		if (regardless || difftime(now, m->lastTouch) > max(client->retryInterval, 10))
		{
			if (m->qos == 1 || (m->qos == 2 && m->nextMessageType == PUBREC))
```

**Comment by cqfive** [comment] 2017-07-04 03:39
Hi guys.
       I have recently encountered a problem about automatic reconnect.I have already set up automaticReconnect, minRetryInterval, maxRetryInterval and struct_version. But when I shut down the server and quickly reopened the server, automatic reconnect did not work.
       Can you teach me how to set up automatic reconnect? Thank you.

**Comment by SeadexWP** [comment] 2017-07-04 09:32
Hi cqfive,

are you using the latest version of the library?
There used to be a problem when you use "too long" timeouts: see issue [#218](https://github.com/eclipse/paho.mqtt.c/issues/218)

**Comment by cqfive** [comment] 2017-07-04 12:53
Thank you for your answer. Help me solve this problem.

**Comment by icraggs** [comment] 2017-07-19 10:53
Isn't the best way to use clock_gettime(CLOCK_MONOTONIC... ) to get the times to calculate time differences (on Linux)?

**Comment by SeadexWP** [comment] 2017-07-20 06:51
Yes, I think so.

**Comment by matthias-stone** [comment] 2017-10-12 21:50
Hello all, I think I can and would like to fix this.

This is similar to an issue I've found in one of my clients' projects with ``MQTTClient``, both of which are symptoms of the larger architectural problem of using wall clock instead of monotonic timers on Linux. I think it makes sense to change all timers as one PR. 

h4. Proposed changes:

* Centralise (almost) all uses of ``time`` and ``gettimeofday`` into a new file, ``MQTTClock.c``.
    * This would mostly be moving the code around ``MQTTClient_start_clock``,
    * Has functions for comparing a clock against elapsed time, etc.
    * Seeding the random number generator would be excluded, as would logging.
* Use a monotonic clock source with ``MQTTClock`` when it is available.
* Replace ``GetTickCount`` with ``GetTickCount64`` on Windows to prevent awkward bugs if someone runs a client for more than 49 days.
* When available, set the monotonic clock attribute for ``pthread_cond_t`` in ``Thread_create_cond``.

h4. Open questions:

* Two functions in ``MQTTProtocolClient`` accept a ``time_t``. These seem to be used exclusively inside the library, so are these function signatures safe to change or should new functions be declared? I'm not very familiar with how this library is packaged, but it appears that external linking to these functions is already discouraged.
* Similarly would changing the types of ``lastTouch``, ``lastSent``, ``lastReceived`` in ``Clients.h`` have any impact on external users of the library?

h4. Limitations:

* The changes I intend to submit will only resolve this issue on Windows and Unix-like systems that have ``CLOCK_MONOTONIC`` present. Note that this excludes OS X, and possibly some minimalist implementations of libc on Linux. I think the solution provides a simple entry point to enable monotonic time on other platforms in the future if someone else wants to do so.
* This will not affect logging or tracing, which might make it more difficult to correlate logs with in memory data structures.

I have very little interest in maintaining a fork, and my client has agreed to developing a solution upstream, but I do need to resolve this in the next couple weeks. Would a PR with the above changes be acceptable, if not are there changes that could be made that would make it more acceptable? @icraggs it seems like you would be the best person to talk to.

**Comment by matthias-stone** [comment] 2017-10-12 21:59
To answer my own questions from above, when packaged it appears none of those headers are included, so I assume they're safe to change without causing compatibility issues.

**Comment by RenaultR42** [comment] 2017-12-11 15:49
I have this issue too on my embedded system, time synchronized over NTP.
Do you have any progress on this topic?

**Comment by matthias-stone** [comment] 2017-12-13 22:21
@RenaultR42 I have, but I was hoping for some feedback on the design before publishing anything.

I'll clean up what I have and try to make it public within the next week.

**Comment by icraggs** [comment] 2017-12-14 00:09
Hi Matthias, very sorry for the slow response - I've been spread a little thin, and I missed your suggestion for change.  I've had a quick read now, which I like the look of.  I'll study in more depth tomorrow.  A PR would be most acceptable.  Ideally we would also have a regression test included although that might be a little tricky.  I can look into an OSX solution, for instance there is a discussion here: https://reformatcode.com/code/objective-c/monotonic-clock-on-osx

**Comment by icraggs** [comment] 2017-12-15 00:05
Open questions:

1. It is safe to change the signatures of the functions within MQTTProtocolClient.c - none of them are used or available externally.

2. Likewise for the structures defined in Clients.h - it is safe to change the time signatures in there.

It all sounds good - and obviously it's important that the existing regression tests continue to run.

**Comment by icraggs** [comment] 2018-06-22 17:31
I've added a fix everywhere except Thread_wait_sem() on Linux, because sem_timedwait() only works with CLOCK_REALTIME.  I hope that this will fix the majority of issues.  If anyone can let me know that would be very helpful.  The fix is in the develop and master branches right now, and will be in a release soon.

**Comment by icraggs** [comment] 2018-08-21 15:43
I had to remove the use of CLOCK_MONOTONIC from Thread_wait_cond() as well, as it didn't work on some platforms.  Same logic as for Thread_wait_sem(): the waits are not long, and repeated frequently,  so not really affected by system clock changes.

**Closed as completed by icraggs** 2018-08-21 15:43 UTC
Labels: bug, fix added
