### ISSUE TITLE
QOS2 messages not being sent in order when sending queued messages after automatic re-connection

### ISSUE THREAD

**Issue by kiran-g** [eclipse-paho/paho.mqtt.c#807] opened 2020-01-30 06:16 UTC
I am implementing persistence module using Paho c++ which deletes a record from a database only when the corresponding data has been successfully published to the cloud or queued internally by paho.  Relevant incomplete code snippet below:

```
    void mqtt_module::start() {
        
        connect();
    
        while (!kill_flag) {
            if(client->is_connected()) {
            records  = read_persistance_database();
                if (records.size() > 0) {
                    for (std::vector<record>::iterator it = records.begin(); it != records.end(); ++it) {
                        try {
                            int* rowid;
                            rowid = new int;
                            *rowid = it->rowid;
                            auto pubmsg = mqtt::make_message(it->topic, it->row_data);
                            pubmsg->set_qos(it->qos);
                            logger->debug("[{}] : [MQTT] publish to topic {} message {}", LOG_TAG,it->topic,it->row_data);
                            client->publish(pubmsg);
                            pubtok->set_user_context(static_cast<void*>(rowid));
                            delete_record(*rowid); //If publish exception doesnt happen, delete record
                            
                        } catch (const mqtt::exception& exc) {
                            break;  //If publish fails, break and read the DB again. this way messages are not sent out of sequence
                        }
                    }
                    records.clear();
                }
            }
            std::this_thread::sleep_for(std::chrono::milliseconds(2000));
        }
    }
    
    void mqtt_module::on_success(const mqtt::token& tok) {
        int* rowid;
        rowid = static_cast<int*>(tok.get_user_context());
        logger->info("Publush success for row {} ",*rowid);
    
    }
    
    
    bool mqtt_module::connect() {
        //callback cb;
        client->set_callback(*this);
    
        mqtt::connect_options connopts(config->mqtt_username, config->mqtt_password);
    
        connopts.set_keep_alive_interval(3);
        connopts.set_connect_timeout(1);
        connopts.set_automatic_reconnect(true);
        connopts.set_clean_session(false);
    
        mqtt::ssl_options sslopts;
        sslopts.set_trust_store(config->mqtt_ca_path);
    
        mqtt::message willmsg(LWT_TOPIC, LWT_PAYLOAD, QOS, true);
        mqtt::will_options will(willmsg);
    
        connopts.set_will(will);
        connopts.set_ssl(sslopts);
    
        try {
            mqtt::token_ptr conntok = client->connect(connopts);
            conntok->wait();
        } catch (const mqtt::exception& exc) {
            logger->debug(exc.what());
            return false;
        }
    
        return true;
    }
    
    void mqtt_module::connection_lost(const string& cause) {
    
    }
    
    void mqtt_module::connected(const std::string& cause) {
    
    }
    
    void mqtt_module::delivery_complete(mqtt::delivery_token_ptr tok) {
    
    }

```
When I test this by disconnecting internet, there is a short duration from the moment at which I disconnect and the moment when paho decides that its disconnected,  when publish does not raise disconnected exception. My understanding is that during this time paho will internally que these messages. When the internet is re-connected it will first send the messages in this queue. My issue is that, when paho sends the messages which were queued during this period , I am seeing out of order messages in the broker, when the QOS is 2. QOS 1 is fine. I am using paho(v1.3.1) and pahocpp(v1.1) . Kindly let me know how to debug/resolve this issue

**Comment by icraggs** [comment] 2020-01-30 11:26
A client library trace of the situation, as suggested in the issue template, would be one way.  Probably at the protocol level to show packet exchange.  

Also a description of the packet ordering you are experiencing.

**Comment by fpagliughi** [comment] 2020-01-30 12:32
Is message ordering guaranteed by the MQTT protocol in any way? Perhaps because I often work with bad connections, I've always assumed that if you send QoS 1&2 messages without waiting for ACKs from each, then they can arrive at the subscriber out of order due to the async nature of the ACK and retry.

So when I depend on ordering, I add a timestamp or incremented ID to the payload.

That said, it would be preferable that the client persistence mechanism kept them in order for re-transmission attempts. But I haven't confirmed that this is happening.

**Comment by icraggs** [comment] 2020-01-30 14:27
The relevant part of the MQTT specification for _inflight_ messages is:

> 4.6 Message ordering

> A Client MUST follow these rules when implementing the protocol flows defined elsewhere in this chapter:
 
> When it re-sends any PUBLISH packets, it MUST re-send them in the order in which the original PUBLISH packets were sent (this applies to QoS 1 and QoS 2 messages) [MQTT-4.6.0-1]
>  It MUST send PUBACK packets in the order in which the corresponding PUBLISH packets were received (QoS 1 messages) [MQTT-4.6.0-2]
 >  It MUST send PUBREC packets in the order in which the corresponding PUBLISH packets were received (QoS 2 messages) [MQTT-4.6.0-3]
>    It MUST send PUBREL packets in the order in which the corresponding PUBREC packets were received (QoS 2 messages) [MQTT-4.6.0-4]

For QoS 2 this does rely on the broker responding to packets in the correct order too.  Also if there is more than one hop involved (client -> broker -> client) then that isn't covered.

So we should resend any unacked inflight messages first, before sending persisted messages.  And for QoS 2 the broker will be resending unacked inflight messages too.  I'd like to get some more details (a protocol level trace) to look at.

**Comment by kiran-g** [comment] 2020-02-03 09:32
I tried to recreate this issue by using a standalone application different from the main application which originally  showed this issue. So far I haven't beem able to create this issue. Will continue testing and update here with more details

**Comment by icraggs** [comment] 2020-06-08 14:27
This seems to be working for me.  There was an issue with ordering of queued messages when restored from persistence (now fixed in the develop branch).  But that would need the client object to be destroyed and recreated.

**Comment by icraggs** [comment] 2020-10-02 15:13
Works for me.

**Closed as completed by icraggs** 2020-10-02 15:13 UTC
Labels: more info needed
