### ISSUE TITLE
Default Persistance UNIX

### ISSUE THREAD

**Issue by croja** [eclipse-paho/paho.mqtt.c#366] opened 2017-11-16 07:47 UTC
Default persistance doesn't handle absolute path (it creates this path as relative, and then fails when trying to open it, returning error -2).
Tested on Linux.

**Comment by icraggs** [comment] 2017-11-16 11:57
Hi.  This is a duplicate of #285.  Thanks.

**Closed as completed by icraggs** 2017-11-16 11:57 UTC
Labels: duplicate
