### ISSUE TITLE
WSS : Websocket connection lost after receiving more than one data at the same time.

### ISSUE THREAD

**Issue by houdarh** [eclipse-paho/paho.mqtt.c#477] opened 2018-06-01 11:08 UTC
After the connection of the client mqtt on websocket (TLS \ SSL), he receives some data and just after he loses the connection (this problem happens if only a lot of data arrive from the server at the same time) but if they are just less than 5 or sometime 10 messages he works well.
And finally he's not reconnect.
[
Connection lost
Reconnecting
Failed to start connecting, return code -6]

Is there someone who has the same problem as me?

thank you in advance,

**Comment by icraggs** [comment] 2018-06-01 11:19
The  websocket support isn't completely tested yet, so this is quite likely to be an issue.  Hopefully this will be addressed in the next few weeks.

**Comment by icraggs** [comment] 2018-08-01 12:24
This should be working now.  If it isn't, taking a trace could help.

**Closed as completed** 2018-08-16 11:22 UTC
Labels: question

**Comment by piotrwach** [comment] 2019-01-10 13:35
I am able to reproduce this problem with version 1.3.0. After subscribing to a topic, and receiving few messages connection is closed. It looks like a bug in Websocket code.

So far I have tracked it down to `MQTTPacket_Factory()` in `MQTTProtocol.c`. The problem is that in this code  `actual_len != remaining_length`, and after retrying few times, connection is closed.

```
/* now read the remaining length, so we know how much more to read */
if ((*error = MQTTPacket_decode(net, &remaining_length)) != TCPSOCKET_COMPLETE)
	goto exit; /* packet not read, *error indicates whether SOCKET_ERROR occurred */

/* now read the rest, the variable header and payload */
data = WebSocket_getdata(net, remaining_length, &actual_len);
if (data == NULL)
{
	*error = SOCKET_ERROR;
	goto exit; /* socket error */
}

if (actual_len != remaining_length)
		*error = TCPSOCKET_INTERRUPTED;
```

**Comment by jumoog** [comment] 2019-01-10 18:16
you picked that commit? 919aeb7cc7058c36efa587f52ff8dd758da5283a

without that commit the Server close the connection after some time.

**Comment by icraggs** [comment] 2019-01-10 19:07
Yes, it's in the develop branch.  It'll be part of the next release.

**Comment by jumoog** [comment] 2019-01-10 19:09
i mean @piotrwach

**Comment by piotrwach** [comment] 2019-01-11 07:14
@jumoog In my case it is the client that closes the connection. When I look at server logs I can see that client sent MQTT DISCONNECT and then closed the socket.

I am still able to reproduce this on develop.

I don't think this problem has something to do with time, in my case connection is closed less than one second after opening it. Client receives a bunch of messages and then decides to disconnect.

**Comment by piotrwach** [comment] 2019-01-11 07:30
Here are the logs, I included only the part after receiving last MQTT message, and then disconnecting.

[log.txt](https://github.com/eclipse/paho.mqtt.c/files/2748524/log.txt)

**Comment by piotrwach** [comment] 2019-01-11 12:41
Looks like the problem is missing caching layer when reading websocket frames.

Example:
Start reading frame from the socket in `WebSocket_receiveFrame`.
Call WebSocket_getRawSocketData to get the opcode, payload length, and then payload itself.
If any of the calls WebSocket_getRawSocketData return TCPSOCKET_INTERRUPTED, we abort, and restart in the next cycle.

Problem:
When next cycle starts, it is going to start reading the frame from where we left of in previous cycle. This is not going to work. Because data coming from the socket is already in the middle of the frame somewhere. 

Solution:
Buffer data coming from the socket, and discard only after whole frame has been read.

**Comment by icraggs** [comment] 2019-01-11 14:07
@piotrwach Can you write a test to show the problem, which we can add to the test suite?  Then we can be sure it gets fixed.

**Comment by icraggs** [comment] 2019-01-31 17:31
@piotrwach  Presumably, you mean that the code as is is expecting one MQTT packet per WebSocket frame?

The travis-build.sh script shows how to run the tests.  

It's confusing to have this discussion in a closed issue.  Now that #609 is open, I suggest carrying it on over there.
