### ISSUE TITLE
Memory leak in subscribeMany5() and possibly other similar methods

### ISSUE THREAD

**Issue by kucalaba** [eclipse-paho/paho.mqtt.c#963] opened 2020-09-29 04:56 UTC
Valgrind reported a memory leak with Paho C MQTTClient library (synchronous) at the following location:
==2130173==    by 0x489F79F: MQTTClient_subscribeMany5 (MQTTClient.c:2025)

Source line MQTTClient.c:2025
`if ((resp.reasonCodes = malloc(sizeof(enum MQTTReasonCodes) * (sub->qoss->count))) == NULL)`

**To Reproduce**
1. Connect a client to a V5.0 broker.
2. Call subscribeMany5() for multiple topics without including any properties.

    Here is my actual invocation to subscribeMany5():
`response = ::MQTTClient_subscribeMany5(mPahoMQTT_ClientHandle, static_cast<int>(rSubscriptionItems.size()),
                &topicNameCharPtrArray.front(), &qualityOfServiceArray.front(), &subscriptionItemOptionsArray.front(), nullptr);`

3. Call MQTTResponse_free(response).

**Expected behavior**
All the memory allocated by Paho C library would be freed.  What actually happened was that zero properties were returned by the V5.0 broker and therefore the reason codes did not get cleaned up.  The reason codes should be separate from the response properties; they are not dependent in any way to each other to my knowledge.

Here is my current workaround in my environment:
static void MQTTResponse_patched_free(::MQTTResponse rResponse)
{
    if(rResponse.properties == nullptr)
    {
        //workaround for memory leak in ::MQTTResponse_free(response)
        if((rResponse.reasonCodeCount > 0) && (rResponse.reasonCodes != nullptr))
        {
            ::MQTTClient_free(rResponse.reasonCodes);
        }
    }
    else
    {
        ::MQTTResponse_free(rResponse);
    }
}
```

** Environment
Ubuntu 20.04.1 (64-bit)

Cheers,
-Luke

**Comment by icraggs** [comment] 2020-09-29 08:43
Is this a duplicate of #962?

**Closed as completed** 2020-09-29 09:05 UTC
Labels: duplicate

**Comment by kucalaba** [comment] 2020-09-29 12:06
Hi Ian,
I only created the one issue. I’ve only ever posted to GitHub a couple times and i tried to improve the readability of the multiline code snippet i pasted.  I was surprised how poorly it rendered and i couldnt find a quick and easy way to fix it. Not sure how a new issue got created though. Sorry about that!  

Thanks,
-Luke
