### ISSUE TITLE
MQTTClient_connect return code does not give good hints on why connect failed 

### ISSUE THREAD

**Issue by cuttlfish** [eclipse-paho/paho.mqtt.c#1040] opened 2021-01-08 19:38 UTC
**Describe the bug**
MQTTClient_connect return -1 for different type of failures. It be nice to get a more concise error code 

**To Reproduce**
For example connecting a invalid server will return -1 as well as connecting to a server with invalid certificate like this error
20210108 193636.818 SSL alert write:fatal:certificate expired
20210108 193636.818 SSL connect:error
20210108 193636.818 (3060595968)      (5)> SSLSocket_error:101
Also return -1
As well as any connection to server with a port blocked all return -1 as error and not able to figure out why the connect failed

**Expected behavior**

** Environment (please complete the following information):**
 - OS: Linux
 - Version 4.9.225-1.18

**Comment by icraggs** [comment] 2021-01-09 12:46
1.  There is an OpenSSL error callback in the SSL options.

2.  This is a duplicate of #937

**Comment by icraggs** [comment] 2021-01-14 12:34
I'm going to track this in #937

**Closed as completed by icraggs** 2021-01-14 12:34 UTC
Labels: duplicate
