### ISSUE TITLE
Previously free()'d ssl handle used to attempt SSLSocket_continueWrite()

### ISSUE THREAD

**Issue by tstock5886** [eclipse-paho/paho.mqtt.c#966] opened 2020-09-29 15:43 UTC
The short background of the problem is that the MQTT code passes a pointer generated by SSL_new() in the SSLSocket.c file back up to SocketBuffer.c. SocketBuffer.c actually makes a copy of the pointer (line 365) and sticks it in a list (global static "writes"). Later on, a SSL partial write (disconnect, or dropped connection or other), in SSLSocket.c (line 931-932), will free the pointer and set it to NULL, but SocketBuffer.c is not informed and will try to use its copy to finish out a partial write. This creates unintended side-effects, obviously.  These side-effects are not consistent. Sometimes the client goes dark - so dark you have to kill -9 to get it shut down. Sometimes it continues to function just fine until the next SSL partial write.

**Comment by tstock5886** [comment] 2020-09-29 15:57
The original "free()" ultimately comes from nextOrClose()->MQTTAsync_closeSession()->MQTTAsync_closeOnly()->SSLSocket_close(); where nextOrClose() was called with -1 and "socket error" for the message.

**Comment by icraggs** [comment] 2020-09-30 09:16
Do you have a test?  The best option is to add to the test suite.

**Comment by icraggs** [comment] 2020-10-21 14:13
I think this could be a duplicate of #944

**Closed as completed** 2020-11-21 20:21 UTC
Labels: duplicate, fix added
