### ISSUE TITLE
MQTTAsync_connect call blocks

### ISSUE THREAD

**Issue by milanzlicic** [eclipse-paho/paho.mqtt.c#1125] opened 2021-07-08 11:49 UTC
While MQTTAsync_processCommand has locked mqttasync_mutex my call to MQTTAsync_connect blocks as it also tries to lock mqttasync_mutex in order to check and start send and receive threads.
The problem is that getaddrinfo, which is called on connect, sometimes hangs for about 30 seconds so my app blocks on call to MQTTAsync_connect since the processing of the previous connect command is hanging.

Is this expected behavior?

**Comment by jumoog** [comment] 2021-07-08 13:26
yes see #915 #690 #1016

**Comment by icraggs** [comment] 2021-07-09 10:43
I'm going to close this as a duplicate of #690 which will track adding the async lookups.

Thanks @jumoog

**Closed as completed** 2021-07-09 10:44 UTC
Labels: duplicate
