### ISSUE TITLE
time issue

### ISSUE THREAD

**Issue by cyqsign** [eclipse-paho/paho.mqtt.c#365] opened 2017-11-16 02:29 UTC
I am using the paho mqtt c library in Linux platform .
But i find MQTTClient_start_clock function use gettimeofday(&start, NULL) instead of clock_gettime(CLOCK_MONOTONIC, &start) in MQTTClient.c/MQTTAsync.c. In AIX platform ,use clock_gettime(CLOCK_REALTIME, &start) instead of clock_gettime(CLOCK_MONOTONIC, &start).My understandings of  CLOCK_MONOTONIC and CLOCK_REALTIME are as follows.
**CLOCK_REALTIME** represents the machine's best-guess as to the current wall-clock, time-of-day time. This means that CLOCK_REALTIME can jump forwards and backwards as the system time-of-day clock is changed, including by NTP.
**CLOCK_MONOTONIC** represents the absolute elapsed wall-clock time since some arbitrary, fixed point in the past. It isn't affected by changes in the system time-of-day clock.
So I think CLOCK_MONOTONIC is the best option.

**Comment by icraggs** [comment] 2017-11-16 11:45
Hi.  This is a duplicate of #284.  I'll close this in favour of the other.  Thanks.

**Closed as completed by icraggs** 2017-11-16 11:45 UTC
Labels: duplicate
