### ISSUE TITLE
MQTTAsync_connectionLost not triggered if packet pending when PING should be sent

### ISSUE THREAD

**Issue by shakespark** [eclipse-paho/paho.mqtt.c#1027] opened 2020-12-30 04:49 UTC
network topology：
A notebook and a device(with mqtt client application) are connected to a network switch，the switch's uplink is connected to LAN, the mqtt broker is also in this LAN.

my clients will call MQTTAsync_sendMessage to publish msg about every 100ms
set keepAliveInterval=10 (seconds)

When I pulled out the switch's uplink cable，after servral menutes, the connlost callback is still not being called.

I checked MQTTProtocol_keepalive in MQTTProtocolClient.c, when network is OK, this function will send send ping, but when network is not OK, this function will not send ping and not check the ping result, because

```
if (Socket_noPendingWrites(client->net.socket))
{   // when network is OK, goes here
    if (MQTTPacket_send_pingreq(&client->net, client->clientID) != TCPSOCKET_COMPLETE)
    {
        Log(TRACE_PROTOCOL, -1, "Error sending PINGREQ for client %s on socket %d, disconnecting", client->clientID, client->net.socket);
        MQTTProtocol_closeSession(client, 1);
    }
    else
    {
// when network is OK, goes here
        client->net.lastPing = now;
        client->ping_outstanding = 1;     //this flag will set to 0 when recv pong
    }
}
else   //add by myself
{
//but when network is not OK, goes here! but there is no process code here
}
```

How to handle this problem? Thank you

 - OS: linux/arm
 - Version: 1.3.7

**Comment by shakespark** [comment] 2020-12-30 08:12
I tried sample code in a x86 ubuntu, it works fine.
I'll figure out why it fails in my arm

**Comment by shakespark** [comment] 2020-12-30 12:37
Quite strange, in my arm device, I run MQTTAsync_publish_time.c serveral times, only 1~2 times the connlost would trigger.
Do you have any hints to solve this problem?

**Comment by icraggs** [comment] 2020-12-30 12:39
Perhaps a trace as described in the readme might show some more information.

**Comment by shakespark** [comment] 2020-12-31 03:53
export MQTT_C_CLIENT_TRACE=ON
export MQTT_C_CLIENT_TRACE_LEVEL=PROTOCOL

for x86 ubuntu, connlost will trigger

> 20201231 113230.246 3 ExampleClientTimePub -> PUBLISH qos: 0 retained: 0 rc: 0 payload len(13): 1609385550246
> 1609385551246
> 20201231 113231.246 3 ExampleClientTimePub -> PUBLISH qos: 0 retained: 0 rc: 0 payload len(13): 1609385551246
> 20201231 113231.338 3 ExampleClientTimePub -> DISCONNECT (-1)
> 
> Connection lost
>      cause: (null)
> Reconnecting

for my arm device, connlost trigger if set publish period for 1~2 senconds，keepAliveInterval=10,PINGREQ will send, connlost will trigger

> 20201231 114145.866 3 ExampleClientTimePub -> PINGREQ (0)
> 1609386105872
> 20201231 114145.872 3 ExampleClientTimePub -> PUBLISH qos: 0 retained: 0 rc: 0 payload len(13): 1609386105872
> 1609386106872
> 20201231 114146.873 3 ExampleClientTimePub -> PUBLISH qos: 0 retained: 0 rc: 0 payload len(13): 1609386106872
> 1609386107873
> 20201231 114147.873 3 ExampleClientTimePub -> PUBLISH qos: 0 retained: 0 rc: 0 payload len(13): 1609386107873
> 1609386108873
> 20201231 114148.874 3 ExampleClientTimePub -> PUBLISH qos: 0 retained: 0 rc: 0 payload len(13): 1609386108873
> 1609386109873
> 20201231 114149.874 3 ExampleClientTimePub -> PUBLISH qos: 0 retained: 0 rc: 0 payload len(13): 1609386109873
> 1609386110874
> 20201231 114150.874 3 ExampleClientTimePub -> PUBLISH qos: 0 retained: 0 rc: 0 payload len(13): 1609386110874
> 1609386111874
> 20201231 114151.875 3 ExampleClientTimePub -> PUBLISH qos: 0 retained: 0 rc: 0 payload len(13): 1609386111874
> 1609386112875
> 20201231 114152.875 3 ExampleClientTimePub -> PUBLISH qos: 0 retained: 0 rc: 0 payload len(13): 1609386112875
> 1609386113875
> 20201231 114153.875 3 ExampleClientTimePub -> PUBLISH qos: 0 retained: 0 rc: 0 payload len(13): 1609386113875
> 1609386114875
> 20201231 114154.876 3 ExampleClientTimePub -> PUBLISH qos: 0 retained: 0 rc: 0 payload len(13): 1609386114875
> 1609386115876
> 20201231 114155.876 3 ExampleClientTimePub -> PUBLISH qos: 0 retained: 0 rc: 0 payload len(13): 1609386115876
> 20201231 114156.875 PINGRESP not received in keepalive interval for client ExampleClientTimePub on socket 3, disconnecting
> 20201231 114156.876 3 ExampleClientTimePub -> DISCONNECT (0)
> 
> Connection lost
>      cause: (null)

but for my arm device, where publish period is set to 10ms(which is the default value in MQTTAsync_publish_time.c), there is a great possibility that the PINGREQ won't send, and then connlost won't trigger.

"ExampleClientTimePub " trace won't print after a few seconds

> 20201231 114646.300 3 ExampleClientTimePub -> PUBLISH qos: 0 retained: 0 rc: 0 payload len(13): 1609386406299
> 1609386406310
> 20201231 114646.310 3 ExampleClientTimePub -> PUBLISH qos: 0 retained: 0 rc: 0 payload len(13): 1609386406310
> 1609386406320
> 20201231 114646.320 3 ExampleClientTimePub -> PUBLISH qos: 0 retained: 0 rc: -22 payload len(13): 1609386406320
> 1609386406330
> 1609386406340
> 1609386406351
> 1609386406361

the last trace show rc: -22, but the log mechanism is quite intrigue that I hasn't found where this trace is printf.

It seems that the performance of my arm device will prevent the PING, I guess some lock will not release?

**Comment by shakespark** [comment] 2020-12-31 07:40
trace level turned to minimum

> 20201231 151959.870 (3065730128)  (1)> MQTTAsync_processCommand:1263
> 20201231 151959.870 (3065730128)   (2)> MQTTProtocol_startPublish:168
> 20201231 151959.870 (3065730128)    (3)> MQTTProtocol_startPublishCommon:145
> 20201231 151959.870 (3065730128)     (4)> MQTTPacket_send_publish:841
> 20201231 151959.871 (3065730128)      (5)> MQTTPacket_sends:256
> 20201231 151959.871 (3065730128)       (6)> MQTTPacket_encode:301
> 20201231 151959.871 (3065730128)       (6)< MQTTPacket_encode:314 (1)
> 20201231 151959.871 (3065730128)       (6)> MQTTPacket_encode:301
> 20201231 151959.871 (3065730128)       (6)< MQTTPacket_encode:314 (1)
> 20201231 151959.871 (3065730128)       (6)> WebSocket_putdatas:944
> 20201231 151959.871 (3065730128)        (7)> Socket_putdatas:520
> 20201231 151959.871 (3065730128)         (8)> Socket_writev:444
> 20201231 151959.871 (3065730128)         (8)< Socket_writev:496 (6)
> 20201231 151959.871 Partial write: 6 bytes of 26 actually written on socket 3
> 20201231 151959.871 (3065730128)         (8)> SocketBuffer_pendingWrite:356
> 20201231 151959.871 (3065730128)         (8)< SocketBuffer_pendingWrite:377 (0)
> 20201231 151959.871 (3065730128)        (7)< Socket_putdatas:573 (-22)
> 20201231 151959.871 (3065730128)       (6)< WebSocket_putdatas:975 (-22)
> 20201231 151959.871 (3065730128)      (5)< MQTTPacket_sends:286 (-22)
> 20201231 151959.871 3 ExampleClientTimePub -> PUBLISH qos: 0 retained: 0 rc: -22 payload len(13): 1609399199870
> 20201231 151959.871 (3065730128)     (4)< MQTTPacket_send_publish:896 (-22)
> 20201231 151959.871 (3065730128)     (4)> MQTTProtocol_storeQoS0:106
> 20201231 151959.871 Storing unsent QoS 0 message
> 20201231 151959.871 (3065730128)      (5)> MQTTProtocol_storePublication:258
> 20201231 151959.874 (3065730128)      (5)< MQTTProtocol_storePublication:279
> 20201231 151959.874 (3065730128)      (5)> SocketBuffer_updateWrite:429
> 20201231 151959.874 (3065730128)      (5)< SocketBuffer_updateWrite:440
> 20201231 151959.874 (3065730128)     (4)< MQTTProtocol_storeQoS0:129
> 20201231 151959.874 (3065730128)    (3)< MQTTProtocol_startPublishCommon:149 (-22)
> 20201231 151959.874 (3065730128)   (2)< MQTTProtocol_startPublish:184 (-22)
> 20201231 151959.874 (3065730128)  (1)< MQTTAsync_processCommand:1651 (1)
> 20201231 151959.874 (3065730128)  (1)> Thread_wait_cond:421

#define TCPSOCKET_INTERRUPTED -22

in this sisuation, ping will not send?

**Comment by wangwenqiangGitHub** [comment] 2021-01-04 12:01
I am shakespark's coworker. When I modify the program as follows: commented code" //if (Socket_noPendingWrites(client->net.socket))" :
`//if (Socket_noPendingWrites(client->net.socket))
if(1)
{   // when network is OK, goes here
    if (MQTTPacket_send_pingreq(&client->net, client->clientID) != TCPSOCKET_COMPLETE)
    {
        Log(TRACE_PROTOCOL, -1, "Error sending PINGREQ for client %s on socket %d, disconnecting", client->clientID, client->net.socket);
        MQTTProtocol_closeSession(client, 1);
    }
    else
    {
// when network is OK, goes here
        client->net.lastPing = now;
        client->ping_outstanding = 1;     //this flag will set to 0 when recv pong
    }
}`
This will trigger after keepAliveInterval passed when the network between client and broker is down .
Can I do that?

**Comment by wangwenqiangGitHub** [comment] 2021-01-04 12:37
when Call this function will erro. Can't reconnect.
```
void connlost(void *context, char *cause)
{
	MQTTAsync client = (MQTTAsync)context;
	MQTTAsync_connectOptions conn_opts = MQTTAsync_connectOptions_initializer;
	int rc;

	printf("\nConnection lost\n");
	printf("     cause: %s\n", cause);

	printf("Reconnecting\n");
	conn_opts.keepAliveInterval = 20;
	conn_opts.cleansession = 1;
	if ((rc = MQTTAsync_connect(client, &conn_opts)) != MQTTASYNC_SUCCESS)
	{
		printf("Failed to start connect, return code %d\n", rc);
 		finished = 1;
	}
}
```

**Comment by wangwenqiangGitHub** [comment] 2021-01-04 12:38
> when Call this function will erro. Can't reconnect.
> 
> ```
> void connlost(void *context, char *cause)
> {
> 	MQTTAsync client = (MQTTAsync)context;
> 	MQTTAsync_connectOptions conn_opts = MQTTAsync_connectOptions_initializer;
> 	int rc;
> 
> 	printf("\nConnection lost\n");
> 	printf("     cause: %s\n", cause);
> 
> 	printf("Reconnecting\n");
> 	conn_opts.keepAliveInterval = 20;
> 	conn_opts.cleansession = 1;
> 	if ((rc = MQTTAsync_connect(client, &conn_opts)) != MQTTASYNC_SUCCESS)
> 	{
> 		printf("Failed to start connect, return code %d\n", rc);
>  		finished = 1;
> 	}
> }
> ```



> I am shakespark's coworker. When I modify the program as follows: commented code" //if (Socket_noPendingWrites(client->net.socket))" :
> `//if (Socket_noPendingWrites(client->net.socket)) if(1) { // when network is OK, goes here if (MQTTPacket_send_pingreq(&client->net, client->clientID) != TCPSOCKET_COMPLETE) { Log(TRACE_PROTOCOL, -1, "Error sending PINGREQ for client %s on socket %d, disconnecting", client->clientID, client->net.socket); MQTTProtocol_closeSession(client, 1); } else { // when network is OK, goes here client->net.lastPing = now; client->ping_outstanding = 1; //this flag will set to 0 when recv pong } }`
> This will trigger after keepAliveInterval passed when the network between client and broker is down .
> Can I do that?

when Call this function will erro. Can't reconnect.

```
void connlost(void *context, char *cause)
{
	MQTTAsync client = (MQTTAsync)context;
	MQTTAsync_connectOptions conn_opts = MQTTAsync_connectOptions_initializer;
	int rc;

	printf("\nConnection lost\n");
	printf("     cause: %s\n", cause);

	printf("Reconnecting\n");
	conn_opts.keepAliveInterval = 20;
	conn_opts.cleansession = 1;
	if ((rc = MQTTAsync_connect(client, &conn_opts)) != MQTTASYNC_SUCCESS)
	{
		printf("Failed to start connect, return code %d\n", rc);
 		finished = 1;
	}
}
```

**Comment by icraggs** [comment] 2021-01-04 15:13
It's because a partial packet has been written to the socket, and stalled.  You can't write another packet like ping to the socket in that case because it would corrupt that half-written socket.

I'm thinking about the correct approach.

**Comment by icraggs** [comment] 2021-01-09 12:50
There are basically two options.

1) close the connection immediately if the ping cannot be written i.e. call closeSession if there are pending writes.  This will work in your case but could be the wrong solution when large packets are being sent.

2) Note that the ping couldn't be sent then try again later and when it's determined the connection really is stalled, then close it.

You can go with option 1) for now.

**Comment by wangwenqiangGitHub** [comment] 2021-01-18 02:49
> There are basically two options.
> 
> 1. close the connection immediately if the ping cannot be written i.e. call closeSession if there are pending writes.  This will work in your case but could be the wrong solution when large packets are being sent.
> 2. Note that the ping couldn't be sent then try again later and when it's determined the connection really is stalled, then close it.
> 
> You can go with option 1) for now.

When I modified as follow:
```
void MQTTProtocol_keepalive(START_TIME_TYPE now)
{
...
else if (MQTTTime_difftime(now, client->net.lastSent) >= (DIFF_TIME_TYPE)(client->keepAliveInterval * 1000) ||
					MQTTTime_difftime(now, client->net.lastReceived) >= (DIFF_TIME_TYPE)(client->keepAliveInterval * 1000))
		{
			if (Socket_noPendingWrites(client->net.socket))
			{
				if (MQTTPacket_send_pingreq(&client->net, client->clientID) != TCPSOCKET_COMPLETE)
				{
					Log(TRACE_PROTOCOL, -1, "Error sending PINGREQ for client %s on socket %d, disconnecting", client->clientID, client->net.socket);
					MQTTProtocol_closeSession(client, 1);
				}
				else
				{
					client->net.lastPing = now;
					client->ping_outstanding = 1;
				}
			}
		}
                else
                {
                MQTTProtocol_closeSession(client, 1);
                }
}
```
When reconnecting, an error will be reported

**Comment by icraggs** [comment] 2021-01-22 13:45
The else in your code should be attached to the line 

    if (Socket_noPendingWrites(client->net.socket))

to be run when the ping can't be written.  It's in the wrong place.

**Comment by zyfromsh** [comment] 2021-01-28 01:30
I meet same issue, but this issue will fixed in 1.3.9 which is late for my project.
is there any workaround or suggestions to avoid this issue or to detect internet down? for example, a way to detect socket error? if the number of message get over buffer(return MQTTASYNC_MAX_BUFFERED_MESSAGES), internet is supposed to be broken?

**Comment by zyfromsh** [comment] 2021-01-28 11:43
if the interval of sending data is 20s, keepalive is 40s, connect lost can't trigger after cable being pulled out.
but keepalive is set to 39s, connect lost can trigger .
so I guess the data and ping are sent at same time. ping maybe blocked by the data, thus connect lost can't be triggered

**Comment by icraggs** [comment] 2021-02-04 12:24
@zyfromsh a workaround is discussed in one of the posts above.  Close the connection in the case the PINGREQ can't be sent due to a packet being written in void MQTTProtocol_keepalive().  It's an over-eager solution but should work for you.

If your project is commercial, you could consider sponsoring my work on this project to help with solutions (Github sponsors - see the pinned issue).

**Comment by icraggs** [comment] 2021-04-30 17:36
Fix added to the develop branch.  Seems to work for me.

**Comment by shakespark** [comment] 2021-05-06 06:45
in the fixed code,
ping_due's default value is 1, ping_due_time's default value is undefined
if there is always send and receice after connect, then no PINGREQ will send, so ping_due will always 1
1.
because ping_due_time's default value is undefined, maybe this will cause running into this code block?
```
		else if (client->ping_due == 1 &&
			(MQTTTime_difftime(now, client->ping_due_time) >= (DIFF_TIME_TYPE)(client->keepAliveInterval * 1000)))
		{
			/* ping still outstanding after keep alive interval, so close session */
			Log(TRACE_PROTOCOL, -1, "PINGREQ still outstanding for client %s on socket %d, disconnecting", client->clientID, client->net.socket);
			MQTTProtocol_closeSession(client, 1);

		}
```
2.
the tcp send buffer maybe full before any PINGREQ is sent, so ping_due will always 1, so this code will never run in
```
			else if (client->ping_due == 0)
			{
				Log(TRACE_PROTOCOL, -1, "Couldn't send PINGREQ for client %s on socket %d, noting",
						client->clientID, client->net.socket);
				client->ping_due = 1;
				client->ping_due_time = now;
			}
```

**Comment by icraggs** [comment] 2021-05-06 10:18
The default for ping_due is 0.  It's initialized in a memset() call for the structure when it's created.  Likewise the ping_time is initialized to 0.  The ": 1" in Clients.h is a bitfield indicator not an intiializer.

I've run a test, and it worked.  As in I reproduced the problem, and the fix fixed it, and the CI test suite ran successfully.   If there's a case you think isn't covered we should have a test for it so we can be sure either way.

**Comment by shakespark** [comment] 2021-05-06 12:28
using automatic reconnect, after plug back the cable and connect successfully, the new added code still report  "PINGREQ still outstanding"
maybe should add some code to reset ping_due and ping_due_time after connected?
```
20210506 193307.212 Calling connected for client OBU-V63121502030000005
then unplug network cable
20210506 193407.781 Couldn't send PINGREQ for client OBU-V63121502030000005 on socket 21, noting
20210506 193508.346 PINGREQ still outstanding for client OBU-V63121502030000005 on socket 21, disconnecting
start autoreconnect
20210506 193540.000 plug back cable
20210506 193543.811 Calling connected for client OBU-V63121502030000005
20210506 193547.008 PINGREQ still outstanding for client OBU-V63121502030000005 on socket 16, disconnecting
20210506 193554.457 Calling connected for client OBU-V63121502030000005
20210506 193557.860 PINGREQ still outstanding for client OBU-V63121502030000005 on socket 16, disconnecting
20210506 193606.547 Calling connected for client OBU-V63121502030000005
20210506 193608.949 PINGREQ still outstanding for client OBU-V63121502030000005 on socket 16, disconnecting
20210506 193615.676 Calling connected for client OBU-V63121502030000005
20210506 193619.068 PINGREQ still outstanding for client OBU-V63121502030000005 on socket 16, disconnecting
20210506 193627.850 Calling connected for client OBU-V63121502030000005
20210506 193630.173 PINGREQ still outstanding for client OBU-V63121502030000005 on socket 16, disconnecting
20210506 193636.902 Calling connected for client OBU-V63121502030000005
20210506 193640.278 PINGREQ still outstanding for client OBU-V63121502030000005 on socket 16, disconnecting
20210506 193645.983 Calling connected for client OBU-V63121502030000005
20210506 193650.458 PINGREQ still outstanding for client OBU-V63121502030000005 on socket 16, disconnecting
20210506 193658.080 Calling connected for client OBU-V63121502030000005
20210506 193701.572 PINGREQ still outstanding for client OBU-V63121502030000005 on socket 16, disconnecting
```

**Comment by icraggs** [comment] 2021-05-07 17:43
Added ping_due reset on close session.

**Comment by shakespark** [comment] 2021-05-08 06:13
It works, thank you!

**Closed as completed** 2021-05-26 09:37 UTC
Labels: fix added
