### ISSUE TITLE
Socket error (Connection Aborted) if publishing a payload equal to / bigger than 128 bytes via websockets

### ISSUE THREAD

**Issue by roscaviktor** [eclipse-paho/paho.mqtt.c#736] opened 2019-10-01 06:16 UTC
It's seems that the connection is aborted (MQTTASYNC_DISCONNECTED) when the TCP Payload has 128 bytes. In Wireshark the frame #956 contains a valid publish request but for the frame #964 the message wasn't correctly built. This defect (Connection Aborted) is always reproduced on my machine (Windows 7 Professional 64-bit) with the attached sample (where HiveMq and Mosquitto brokers were used). Maybe there is a problem in WebSocket_buildFrame or WebSocket_calculateFrameHeaderSize functions.

**MQTTAsync_publish.c sample**
![2019-10-01 09_00_33-Microsoft Visual Studio Debug Console](https://user-images.githubusercontent.com/12120314/65938173-1fa6a700-e3d7-11e9-939d-665c75a31e26.png)
[MQTTAsync_publish.zip](https://github.com/eclipse/paho.mqtt.c/files/3674668/MQTTAsync_publish.zip)

**Wireshark capture** 

_frame #956_
![2019-10-01 09_04_18-wireshark pca](https://user-images.githubusercontent.com/12120314/65938174-1fa6a700-e3d7-11e9-9c07-edd335f374f4.png)

_frame #964_ 
![2019-10-01 09_04_50-wireshark pca](https://user-images.githubusercontent.com/12120314/65938171-1f0e1080-e3d7-11e9-9cdc-ece95f4fbc30.png)

![2019-10-01 09_05_17-wireshark pca](https://user-images.githubusercontent.com/12120314/65938172-1f0e1080-e3d7-11e9-8dcb-7b25bcd2fda9.png)
[wireshark.zip](https://github.com/eclipse/paho.mqtt.c/files/3674667/wireshark.zip)

**Comment by icraggs** [comment] 2019-11-29 12:25
There are some issues with the websocket support with larger payloads, although in my testing the limit was larger than 128.  My testing was on Linux mind you.

**Comment by icraggs** [comment] 2019-11-29 12:27
I'm going to close this as a duplicate of #721 to track the problem.

**Closed as completed by icraggs** 2019-11-29 12:27 UTC
Labels: bug, duplicate
