### ISSUE TITLE
MQTTAsync_isConnected() blocks

### ISSUE THREAD

**Issue by xhpohanka** [eclipse-paho/paho.mqtt.c#1016] opened 2020-12-09 08:22 UTC
I would expect that an async client should be asynchronous by nature but it seems that many calls can be blocking.
Actually I got burnt by `MQTTAsync_isConnected` call that can block for a long time if there is an issue with connecting.

Is it an intended behavior? I know I can introduce my own `is_connected` flag and set it in a callback but it looks like a duplicating of already existing code to me.

**Comment by icraggs** [comment] 2020-12-09 17:13
"Many" calls can be blocking?  I don't think that's true.  I added WaitForCompletion() as a request, against my better judgement.  

I presume the "issue with connecting" is if the DNS lookup takes a while.  This is the only synchronous operation.  It wasn't added originally as there was no way (and I think this is still true) to accomplish DNS lookups in an cross platform, non-threaded, non-blocking way.  There are alternatives, but it's a non-trivial amount of work #915.  We're open to PRs.

**Comment by icraggs** [comment] 2020-12-12 11:46
I'm going to say this is a duplicate of #915 unless any further information arises.

**Comment by xhpohanka** [comment] 2020-12-13 14:08
It probably is, ok

Dne so 12. 12. 2020 12:46 uživatel Ian Craggs <notifications@github.com>
napsal:

**Closed as completed** 2020-12-15 07:06 UTC
Labels: duplicate

**Comment by killerkalamari** [comment] 2023-05-10 14:34
Ran into this issue the other day. As an experiment, I connected via IP address. This did seem to bypass the problem, but in order to connect that way I had to set the `verify` field of `MQTTAsync_SSLOptions` to `0`, which would have left the client open to MITM attacks. Probably not an ideal tradeoff.

Is it possible to specify the length of time the library blocks DNS calls for? I'm running on Linux. I saw there was work toward using `getaddrinfo_a`, but I wasn't sure if that was fully functioning or not. I didn't see any way of configuring it, if so.

If not, is it possible for me to issue `MQTTAsync_isConnected()` calls in a separate thread, while I'm still calling other MQTTAsync functions in the main thread, or is the library not designed for that? Would it help if every call I made into the library was protected by a mutex or such so that only one MQTTAsync call happens at a time?

What if I performed the DNS lookup myself and gave that IP address as part of the `serverURI` arg to `MQTTAsync_create()`, but then also told the library somehow (new functionality) that I resolved that IP myself from the hostname (and what the hostname was)? Then, in that new mode, I could set the `verify` field of `MQTTAsync_SSLOptions` to `1` and have the library do hostname checking. Or would that not prevent a MITM attack?

**Comment by icraggs** [comment] 2023-05-11 11:56
@killerkalamari there is some code in Socket.c to have a timeout on DNS calls but I commented it out a while back because it caused errors I couldn't track down at the time. 

I think that the best solution is to implement async DNS lookups.
